// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjRjFAZgxDyFpNPpDcGqbGc0OSNyhtks4',
    appId: '1:1045127042203:web:a23d2708aa0e42a349a23e',
    messagingSenderId: '1045127042203',
    projectId: 'beta-testing-fffc5',
    authDomain: 'beta-testing-fffc5.firebaseapp.com',
    storageBucket: 'beta-testing-fffc5.firebasestorage.app',
    measurementId: 'G-T56HN862SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBvqgIDNPgOYfxYLYWw4prK6-JG3VuqU',
    appId: '1:1045127042203:android:1098431fd195f6c249a23e',
    messagingSenderId: '1045127042203',
    projectId: 'beta-testing-fffc5',
    storageBucket: 'beta-testing-fffc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjR3xM7DrxJarkfgUWzSub1RK3_2FuwpU',
    appId: '1:1045127042203:ios:ddceb7f46efb7fb149a23e',
    messagingSenderId: '1045127042203',
    projectId: 'beta-testing-fffc5',
    storageBucket: 'beta-testing-fffc5.firebasestorage.app',
    iosBundleId: 'com.example.betaTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjR3xM7DrxJarkfgUWzSub1RK3_2FuwpU',
    appId: '1:1045127042203:ios:ddceb7f46efb7fb149a23e',
    messagingSenderId: '1045127042203',
    projectId: 'beta-testing-fffc5',
    storageBucket: 'beta-testing-fffc5.firebasestorage.app',
    iosBundleId: 'com.example.betaTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjRjFAZgxDyFpNPpDcGqbGc0OSNyhtks4',
    appId: '1:1045127042203:web:4ad9b353ac00798249a23e',
    messagingSenderId: '1045127042203',
    projectId: 'beta-testing-fffc5',
    authDomain: 'beta-testing-fffc5.firebaseapp.com',
    storageBucket: 'beta-testing-fffc5.firebasestorage.app',
    measurementId: 'G-3LZ3M1LGSN',
  );

}